controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

alcohols_list:
    path: /alcohols
    controller: App\Controller\AlcoholController::listAlcohols
    methods: GET
